#!/usr/bin/env node
/**
 * Vendoring sync — single source of truth for the copies under `cli/vendor/`.
 *
 * Copies the canonical scripts/schema out of the monorepo into `vendor/` as
 * byte-exact copies, and (re)generates `vendor/README.md`. Idempotent: running
 * it twice produces no diff. A drift test asserts the copies match their
 * sources; this script is how you fix drift.
 *
 * Run from anywhere: `npm run sync` (or `node scripts/sync.mjs`).
 *
 * Exit codes: 0 success · 1 a canonical source was missing.
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { fileURLToPath, pathToFileURL } from "node:url";
import { dirname, resolve, relative } from "node:path";

const HERE = dirname(fileURLToPath(import.meta.url)); // <pkg>/scripts
const PKG_ROOT = resolve(HERE, "..");
const REPO_ROOT = resolve(PKG_ROOT, ".."); // monorepo root
const VENDOR_DIR = resolve(PKG_ROOT, "vendor");

/**
 * Canonical source (repo-root-relative) → vendored basename.
 * This mapping is duplicated by test/vendor.test.mjs as the drift contract.
 */
export const VENDOR_MAP = [
  { source: ".claude/skills/onboard/prepass.mjs", vendored: "prepass.mjs" },
  { source: ".claude/skills/onboard/edges-check.mjs", vendored: "edges-check.mjs" },
  { source: "schema/analysis.schema.json", vendored: "analysis.schema.json" },
  { source: "schema/validate-core.mjs", vendored: "validate-core.mjs" },
  { source: "schema/export-markdown.mjs", vendored: "export-markdown.mjs" },
];

function generateReadme() {
  const rows = VENDOR_MAP.map(
    (m) => `| \`${m.vendored}\` | \`${m.source}\` |`,
  ).join("\n");
  return `# vendor/ — generated by scripts/sync.mjs — do not edit

These files are **byte-exact copies** of canonical sources in the
repo-onboarding monorepo. Do not edit them here. Edit the source and run
\`npm run sync\` to refresh; a test fails if they drift.

| vendored file | canonical source |
| --- | --- |
${rows}
`;
}

export function main() {
  mkdirSync(VENDOR_DIR, { recursive: true });

  let missing = 0;
  for (const { source, vendored } of VENDOR_MAP) {
    const srcPath = resolve(REPO_ROOT, source);
    if (!existsSync(srcPath)) {
      console.error(`missing canonical source: ${source}`);
      missing++;
      continue;
    }
    const buf = readFileSync(srcPath);
    const destPath = resolve(VENDOR_DIR, vendored);
    // Only write when bytes differ so the mtime (and any watchers) stay quiet.
    let changed = true;
    if (existsSync(destPath) && readFileSync(destPath).equals(buf)) {
      changed = false;
    } else {
      writeFileSync(destPath, buf);
    }
    console.error(
      `${changed ? "synced " : "ok     "} vendor/${vendored}  <-  ${relative(REPO_ROOT, srcPath).split("\\").join("/")}`,
    );
  }

  const readmePath = resolve(VENDOR_DIR, "README.md");
  const readme = generateReadme();
  if (!existsSync(readmePath) || readFileSync(readmePath, "utf8") !== readme) {
    writeFileSync(readmePath, readme, "utf8");
    console.error("synced  vendor/README.md");
  } else {
    console.error("ok      vendor/README.md");
  }

  if (missing > 0) {
    console.error(
      `\nsync FAILED: ${missing} canonical source(s) missing. ` +
        "Run this from inside the repo-onboarding monorepo.",
    );
    process.exit(1);
  }
}

// Only run when executed directly (so tests can import VENDOR_MAP safely).
const invokedDirectly =
  process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href;
if (invokedDirectly) main();
